# Configuration pour MongoDB en Docker
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=cooking_recipes

# Configuration pour production
logging.level.root=INFO
logging.level.com.example.recipes=INFO